-- Refactored Database Schema for Laravel Migrations
-- Generated by Claude Database Architect
-- Original File: demDB.sql

SET FOREIGN_KEY_CHECKS = 0;

-- =============================================================================
-- LEVEL 0: INDEPENDENT MASTER DATA
-- =============================================================================

CREATE TABLE `pays` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `alpha2` VARCHAR(6) NOT NULL,
  `alpha3` VARCHAR(9) NOT NULL,
  `nom_ar` VARCHAR(135) NOT NULL,
  `nom_fr` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `alpha2_unique` (`alpha2`),
  UNIQUE KEY `alpha3_unique` (`alpha3`),
  UNIQUE KEY `code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wilayas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `communes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(135) NOT NULL,
  `wilaya_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_communes_wilayas` FOREIGN KEY (`wilaya_id`) REFERENCES `wilayas` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `situation_familiale` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `postes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `poste_fr` VARCHAR(600) NOT NULL,
  `poste_ar` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `type_service` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `type_etablissement` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `piece_identite` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_piece` VARCHAR(135) NOT NULL,
  `numero` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- LEVEL 1: CORE ENTITIES
-- =============================================================================

CREATE TABLE `personne` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricule` VARCHAR(45) DEFAULT NULL,
  `nom` VARCHAR(135) DEFAULT NULL,
  `prenom` VARCHAR(135) DEFAULT NULL,
  `nom_ar` VARCHAR(135) DEFAULT NULL,
  `prenom_ar` VARCHAR(135) DEFAULT NULL,
  `poste_id` BIGINT UNSIGNED DEFAULT NULL,
  `est_consultant` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_personne_postes` FOREIGN KEY (`poste_id`) REFERENCES `postes` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `patient` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricule_patient` VARCHAR(54) DEFAULT NULL,
  `nin` VARCHAR(765) NOT NULL,
  `nom` VARCHAR(135) DEFAULT NULL,
  `prenom` VARCHAR(135) DEFAULT NULL,
  `prenom_ar` VARCHAR(135) DEFAULT NULL,
  `nom_ar` VARCHAR(135) DEFAULT NULL,
  `genre` VARCHAR(10) DEFAULT NULL,
  `date_naissance` DATETIME DEFAULT NULL,
  `lieu_naissance_id` BIGINT UNSIGNED DEFAULT NULL,
  `prenom_pere` VARCHAR(135) DEFAULT NULL,
  `nom_mere` VARCHAR(135) DEFAULT NULL,
  `prenom_mere` VARCHAR(135) DEFAULT NULL,
  `prenom_pere_ar` VARCHAR(135) DEFAULT NULL,
  `nom_mere_ar` VARCHAR(135) DEFAULT NULL,
  `prenom_mere_ar` VARCHAR(135) DEFAULT NULL,
  `nationalite_id` BIGINT UNSIGNED DEFAULT NULL,
  `situation_familiale_id` BIGINT UNSIGNED NOT NULL,
  `conjoin_id` BIGINT UNSIGNED DEFAULT NULL,
  `ins` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `matricule_patient_unique` (`matricule_patient`),
  CONSTRAINT `fk_patient_communes` FOREIGN KEY (`lieu_naissance_id`) REFERENCES `communes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_patient_pays` FOREIGN KEY (`nationalite_id`) REFERENCES `pays` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_patient_situation` FOREIGN KEY (`situation_familiale_id`) REFERENCES `situation_familiale` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `acompagne` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(135) DEFAULT NULL,
  `prenom` VARCHAR(135) DEFAULT NULL,
  `adresse` VARCHAR(135) DEFAULT NULL,
  `telephone` VARCHAR(135) DEFAULT NULL,
  `piece_identite_id` BIGINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_acompagne_piece` FOREIGN KEY (`piece_identite_id`) REFERENCES `piece_identite` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- LEVEL 2: ORGANIZATIONAL STRUCTURE
-- =============================================================================

CREATE TABLE `etab_unite` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_unite` VARCHAR(135) NOT NULL,
  `type_etab_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_unite_type` FOREIGN KEY (`type_etab_id`) REFERENCES `type_etablissement` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_service` VARCHAR(135) DEFAULT NULL,
  `chef_id` BIGINT UNSIGNED DEFAULT NULL,
  `medecin_chef_id` BIGINT UNSIGNED DEFAULT NULL,
  `type_service_id` BIGINT UNSIGNED DEFAULT NULL,
  `type_admission` INT NOT NULL,
  `etab_unite_id` BIGINT UNSIGNED NOT NULL,
  `duree_max` INT DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_services_chef` FOREIGN KEY (`chef_id`) REFERENCES `personne` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_services_medchef` FOREIGN KEY (`medecin_chef_id`) REFERENCES `personne` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_services_type` FOREIGN KEY (`type_service_id`) REFERENCES `type_service` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_services_unite` FOREIGN KEY (`etab_unite_id`) REFERENCES `etab_unite` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- LEVEL 3: TRANSACTIONAL DATA (ADMISSIONS & CLINICAL)
-- =============================================================================

CREATE TABLE `admission` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `date_admission` DATETIME NOT NULL,
  `date_sortie` DATETIME DEFAULT NULL,
  `motif_admission` TEXT,
  `statut` VARCHAR(50) DEFAULT 'active',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admission_patient` FOREIGN KEY (`patient_id`) REFERENCES `patient` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_admission_service` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `acte_prescrit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admission_id` BIGINT UNSIGNED NOT NULL,
  `personne_id` BIGINT UNSIGNED NOT NULL,
  `acte_id` BIGINT UNSIGNED NOT NULL,
  `date_prescription` DATETIME NOT NULL,
  `notes` TEXT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_acte_adm` FOREIGN KEY (`admission_id`) REFERENCES `admission` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_acte_pers` FOREIGN KEY (`personne_id`) REFERENCES `personne` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_acte_type` FOREIGN KEY (`acte_id`) REFERENCES `actes` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fiche_suivi` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admission_id` BIGINT UNSIGNED NOT NULL,
  `personne_id` BIGINT UNSIGNED NOT NULL,
  `date_suivi` DATETIME NOT NULL,
  `observations` TEXT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_suivi_adm` FOREIGN KEY (`admission_id`) REFERENCES `admission` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_suivi_pers` FOREIGN KEY (`personne_id`) REFERENCES `personne` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `diagnostic_detecte` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admission_id` BIGINT UNSIGNED DEFAULT NULL,
  `personne_id` BIGINT UNSIGNED NOT NULL,
  `diagnostic_id` BIGINT UNSIGNED DEFAULT NULL,
  `date_diagnostic` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_diag_adm` FOREIGN KEY (`admission_id`) REFERENCES `admission` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_diag_pers` FOREIGN KEY (`personne_id`) REFERENCES `personne` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- ACTES REFERENCE TABLE
-- =============================================================================

CREATE TABLE `actes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `designation` VARCHAR(255) NOT NULL,
  `prix` DECIMAL(10,2) DEFAULT 0.00,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
